// Generated by k6-browser-test
/**
 * k6 browser FUNCTIONAL test — single iteration, expect() assertions.
 *
 * This is the default shape: prove a user journey works correctly. One VU, one
 * iteration, hard assertions that abort on failure.
 *
 * CONVENTIONS (see references/browser-best-practices.md):
 * - Default export MUST be async; interactions are awaited.
 * - Navigate with waitUntil:'load' (NOT 'networkidle' — analytics/chat-heavy
 *   sites never go idle and it times out).
 * - Dismiss any cookie/consent banner as the first action (resolve the exact
 *   control during exploration; the line below is a placeholder).
 * - Interact directly: getBy* locators auto-wait for actionability. Do NOT add
 *   waitFor() before a click/fill, and do NOT call waitForLoadState().
 * - Assertions use expect() from k6-testing — matchers auto-retry on locators.
 * - Always close the page in finally.
 * - Screenshot after each navigation/action and before assertions, with unique
 *   numbered paths; k6 auto-creates the screenshots/ dir. Omit if unwanted.
 *
 * SELECTOR PRIORITY: getByRole > getByLabel > getByText > getByPlaceholder >
 * getByTestId > CSS attribute fallback (locator('[data-test="…"]'),
 * locator('input[name="…"]')) > structural CSS (last resort, brittle).
 * Resolve real selectors by exploring the live site — see references/explore.md.
 */
import { browser } from 'k6/browser';
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';

export const options = {
  scenarios: {
    ui: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
      options: { browser: { type: 'chromium' } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  try {
    await page.goto('https://quickpizza.grafana.com', { waitUntil: 'load' });
    await page.screenshot({ path: 'screenshots/01-home.png' });

    // If the site shows a cookie/consent banner, dismiss it first. Resolve the
    // exact button while exploring, e.g.:
    // await page.getByRole('button', { name: 'Accept all' }).click();

    // Interact directly — the locator waits for the button to be actionable.
    await page.getByRole('button', { name: 'Pizza, Please!' }).click();
    await page.screenshot({ path: 'screenshots/02-after-click.png' }); // documents pre-assert state

    // expect() retries against the locator until it passes or times out. This
    // single line replaces the waitFor() + isVisible() + check() anti-pattern.
    // Headings are a role too — getByRole('heading') is clearer than getByText.
    await expect(page.getByRole('heading', { name: 'Our recommendation:' })).toBeVisible();

    // Other retrying matchers you can use:
    // await expect(page.getByText('Our recommendation:')).toBeVisible();
    // await expect(page).toHaveTitle(/QuickPizza/);
    // await expect(page.locator('[data-test="cart-badge"]')).toHaveText('1'); // data-test → CSS
    // await expect(page.getByRole('button', { name: 'Love it!' })).toBeEnabled();
  } finally {
    await page.close();
  }
}
