// Generated by k6-browser-test
/**
 * k6 browser LOAD test — multiple browser VUs + Core Web Vitals thresholds.
 *
 * Use this shape only when the user asks for load/performance signal from real
 * browsers (not just a functional pass/fail). Browser VUs are expensive —
 * keep counts modest and pair with protocol load tests for high throughput.
 *
 * Same conventions as the functional example (async, waitUntil:'load', direct
 * interaction, try/finally), plus:
 * - A ramping-vus scenario with an exported `ui` function.
 * - Core Web Vitals thresholds at p75 (the percentile CWV are assessed at) so the
 *   run can fail in CI on a regression.
 * - Think time via page.waitForTimeout() (browser scripts use this, not sleep()).
 * - Screenshots GATED to the first iteration + on failure: a screenshot per
 *   iteration under load floods the disk and its latency biases the Web Vitals.
 */
import { browser } from 'k6/browser';
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';
import exec from 'k6/execution';

export const options = {
  scenarios: {
    ui: {
      executor: 'ramping-vus',
      exec: 'ui',
      startVUs: 0,
      stages: [
        { duration: '30s', target: 3 },
        { duration: '1m', target: 3 },
        { duration: '15s', target: 0 },
      ],
      options: { browser: { type: 'chromium' } },
    },
  },
  thresholds: {
    // Google "good" Core Web Vitals, at the 75th percentile (how CWV are graded):
    browser_web_vital_lcp: ['p(75)<2500'], // Largest Contentful Paint (ms)
    browser_web_vital_inp: ['p(75)<200'], // Interaction to Next Paint (ms)
    browser_web_vital_cls: ['p(75)<0.1'], // Cumulative Layout Shift (score)
  },
};

export async function ui() {
  const page = await browser.newPage();
  // Capture screenshots on the FIRST iteration only — under load, a screenshot
  // per iteration floods the disk and its latency biases the Web Vitals.
  const shoot = exec.scenario.iterationInTest === 0;

  try {
    await page.goto('https://quickpizza.grafana.com', { waitUntil: 'load' });
    if (shoot) await page.screenshot({ path: 'screenshots/load-01-home.png' });

    // Dismiss consent here if the site shows one (resolve during exploration).

    await page.getByRole('button', { name: 'Pizza, Please!' }).click();

    // expect() is a functional-test tool: it throws on failure and aborts the
    // whole iteration. Keep at most one cheap sanity assertion here — the Web
    // Vitals thresholds above are what should fail a load run.
    await expect(page.getByRole('heading', { name: 'Our recommendation:' })).toBeVisible();
    if (shoot) await page.screenshot({ path: 'screenshots/load-02-recommendation.png' });

    await page.waitForTimeout(1000); // user think time
  } catch (err) {
    // Always capture a failing iteration (unique path so concurrent VUs don't
    // clobber each other); best-effort so a screenshot error can't mask `err`.
    try {
      await page.screenshot({
        path: `screenshots/load-fail-vu${exec.vu.idInTest}-iter${exec.scenario.iterationInTest}.png`,
      });
    } catch (_) {
      // ignore — the original error is what matters
    }
    throw err;
  } finally {
    await page.close();
  }
}
